services:
  _defaults:
    autowire: true

  _instanceof:
    HeimrichHannot\GoogleChartsBundle\Chart\ChartInterface:
      tags: ['huh.google_charts.chart']

    HeimrichHannot\GoogleChartsBundle\DataType\DataTypeInterface:
      tags: ['huh.google_charts.data_type']

  HeimrichHannot\GoogleChartsBundle\:
    resource: '../../{EventListener}/*'
    autowire: true
    autoconfigure: true

# Choice
  huh.google_charts.choice.template.chart:
    class: HeimrichHannot\GoogleChartsBundle\Choice\ChartTemplateChoice
    public: true


# Manager

  huh.google_charts.manager.google_charts:
    class: HeimrichHannot\GoogleChartsBundle\Manager\GoogleChartsManager
    public: true
  HeimrichHannot\GoogleChartsBundle\Manager\GoogleChartsManager: '@huh.google_charts.manager.google_charts'

# Charts

  HeimrichHannot\GoogleChartsBundle\Chart\Concrete\LineChart: ~


# DataTypes

  HeimrichHannot\GoogleChartsBundle\DataType\Concrete\DataTypeJson: ~
  HeimrichHannot\GoogleChartsBundle\DataType\Concrete\DataTypeReference: ~
  HeimrichHannot\GoogleChartsBundle\DataType\Concrete\DataTypeContextual: ~